# Changes here will be overwritten by Copier
AddAllcontributors: false
AddCitationCFF: false
AddCodeOfConduct: false
AddCompatHelperCI: true
AddContributionDocs: false
AddCopierCI: false
AddDependabot: true
AddDocs: true
AddDocsCI: true
AddFormatterAndLinterConfigFiles: false
AddGitHubPRTemplate: true
AddGitHubTemplates: false
AddLintCI: false
AddLychee: false
AddMacToCI: false
AddTagBotCI: true
AddTestCI: true
AddWinToCI: false
Authors: XuanzheXia <hzxiaxz@gmail.com>
AutoIncludeTests: false
CheckExplicitImports: false
JuliaMinCIVersion: lts
JuliaMinVersion: '1.10'
License: MIT
LicenseCopyrightHolders: hz-xiaxz
PackageName: FFS
PackageOwner: hz-xiaxz
PackageUUID: 7138107a-3882-4a4c-937b-b185d0f51c68
RunJuliaNightlyOnCI: false
StrategyConfirmIncluded: true
StrategyLevel: 1
StrategyReviewExcluded: true
UseCirrusCI: false
_commit: v0.16.2
_src_path: https://github.com/JuliaBesties/BestieTemplate.jl
