name = "FastFermionSampling"
uuid = "7138107a-3882-4a4c-937b-b185d0f51c68"
authors = ["XuanzheXia"]
version = "1.0.0-DEV"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
